spring:
  application:
    name: SeaBattleServer

  datasource:
    url: jdbc:postgresql://localhost:5432/battleship_db
    username: battleship_user
    password: battleship_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        connection:
          charSet: UTF-8
    hibernate:
      ddl-auto: create
      show-sql: true

jwt:
  secret: MY_SUPER_SECRET_KEY_1234567890_ABCDEF
  expiration-ms: 3600000

logging:
  file:
    name: logs/seabattle.log
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


server:
  address: 0.0.0.0
  port: 8080